 do sp_conexion
public mcon3, mc,ant,ef
ef ="PACIENTE EN DECUBITO DORSAL BAJO ANESTESIA GENERAL EN MESA TRASLUCIDA, ASEPSIA Y ANTISEPSIA DEL MIEMBRO INFERIOR DERECHO. EMBROCADO "+;
"Y COLOCACION DE CAMPOS QUIRURGICOS, ABORDAJE DE RODILLA PARAROTULIANO INTERNO,  DISECCION POR PLANOS. SE OBTIENE LIQUIDO "+;
"INTRARTICULAR EL CUAL SE TOMAN MUESTRAS PARA SU ANALISIS. RESECCION DE ROTULA, RETIRO DE PROTESIS DE RODILLA."+chr(10)+;
"RETIRO DE CEMENTO REMANENTE. SE TOMAN MUESTRAS DE PSEUDOMEMBRANA Y TEJIDO REMANENTE. "+chr(10)+;
"LIMPIEZA ARTICULAR. "+chr(10)+;
"SE INICA POR FOSITA DIGITAL INTRODUCCION DE LAS GUIAS DE FRESADO. SE REALIZA FRESADO PROGREESIVO DE TIBIA Y FEMUR. SE FRESA FEMUR 14MM Y TIBIA 12MM "+chr(10)+;
"SE COLOCA CLAVO MACIZO DE ACERO PARA ARTRODESIS DE RODILLA DE 850MM DE LONGUITUD POR 12 Y 11 MM. SE REALIZA ACERROJAOD A PROXIMAL Y DISTAL "+;
"CON DOS TORNILLOS DE BLOQUEO. SE COMPRUEBA CORRECTA COLOCACION DE CERROJOS. TODO BAJO CONTROL D ERX. "+chr(10)+;
"SE COLOCA INJERTO DE ROTULA AUTOLOGA EN CHIPS + BLOCK MACISO PARA RELLENO DE DEFECTO OSEO EN FEMUR DISTAL Y TIBIA PROXIMAL. "+chr(10)+;
"LAVADO PROFUSO CON SOLUCION FISIOLOGICA. "+chr(10)+;
"CIERRE POR PLANOS. CORRECTA HEMOSTASIA. SE COLOCA SUCTOR. CURACION PLANA. VENDAJE ESTERIL. TODO SEGUN TECNICA QUIRURGICA."+chr(10)

SET STEP ON

mret=sqlexec(mcon1," update  Tabquiroproto set TQP_DESCCIRU =?ef  "+;
	" where id =  45745")
	***eg_evolhist = ?mevolh "+; &&EG_motConsulta = ?mc , 
*!*	mievol = "Debido al tiempo de evolucion e impresion quirurgica se decide con acuerdo del dr Selandari, jefe de servicio de pediatria "+;
*!*	" comenzar tto empirico con cefalexina 2 gr por dia por 10 dias + "+;
*!*	"ibuprofeno 400 mg cada 6 hs y crioterapia y citar para eco y control clinico el sabado por la mañana."
*!*	mret=sqlexec(mcon1," update  TabGuaEvolmed set EGM_evol = ?mievol"+;
*!*	" where id =  2173662")

do sp_desconexion

