select COUNT(TCS_IPADDRESS),TCS_CLIENTNAME  FROM TABCTRSRV GROUP BY TCS_CLIENTNAME INTO CURSOR CTRL
SELECT * FROM TABCTRSRV  WHERE TCS_CLIENTNAME IN ()select TCS_CLIENTNAME from ctrl) into cursor varios
SELECT * FROM TABCTRSRV  WHERE TCS_CLIENTNAME IN (select TCS_CLIENTNAME from ctrl) into cursor varios
brows
copy to duplicados type xls
SELECT 22
BROWSE LAST
SELECT * FROM TABCTRSRV  WHERE TCS_CLIENTNAME IN (select TCS_CLIENTNAME from ctrl where cnt_TCS_IPADDRESS>1) into cursor varios
BROWSE LAST
copy to duplicados type xls
