DEFINE PAD _2F90Y516F OF _MSYSMENU  SALIR  COLOR SCHEME 3
DEFINE PAD _2F90Y516G OF _MSYSMENU  CONFIGURACION  COLOR SCHEME 3
DEFINE PAD _2F90Y516H OF _MSYSMENU  TABLAS VARIAS  COLOR SCHEME 3
DEFINE PAD _2F90Y516I OF _MSYSMENU  PROFESIONALES  COLOR SCHEME 3
DEFINE PAD _2F90Y516J OF _MSYSMENU  MANEJO DE AGENDA  COLOR SCHEME 3
DEFINE PAD _2F90Y516K OF _MSYSMENU  ESTADISTICAS  COLOR SCHEME 3
DEFINE PAD _2F90Y516L OF _MSYSMENU  TURNOS  COLOR SCHEME 3
ON PAD _2F90Y516F OF _MSYSMENU ACTIVATE POPUP SALIR
ON PAD _2F90Y516G OF _MSYSMENU ACTIVATE POPUP CONFIGURAC
ON PAD _2F90Y516H OF _MSYSMENU ACTIVATE POPUP TABLASVARI
ON PAD _2F90Y516I OF _MSYSMENU ACTIVATE POPUP PROFESIONA
ON PAD _2F90Y516J OF _MSYSMENU ACTIVATE POPUP MANEJODEAG
ON PAD _2F90Y516K OF _MSYSMENU ACTIVATE POPUP ESTADISTIC
ON PAD _2F90Y516L OF _MSYSMENU ACTIVATE POPUP TURNOS


DEFINE POPUP TABLASVARI MARGIN RELATIVE SHADOW COLOR SCHEME 4
  1 OF TABLASVARI  MENSAJES EN TURNOS
  2 OF TABLASVARI  AVISOS POR ENTIDADES
  3 OF TABLASVARI  VALORES COSEGUROS
  4 OF TABLASVARI  PREPARACIONES
  5 OF TABLASVARI  MENSAJES EN WEB
  6 OF TABLASVARI  \-
  7 OF TABLASVARI  ACTUALIZAR FRANJA HORARIA
  8 OF TABLASVARI  ACTUALIZAR FERIADOS
  9 OF TABLASVARI  ACTUALIZAR CONSULTORIOS
  10 OF TABLASVARI  \-
  11 OF TABLASVARI  BONOS
  12 OF TABLASVARI  \-
  13 OF TABLASVARI  MODIFICACIONES ESPECIALES PACIENTE
  14 OF TABLASVARI  UNIFICACION DE H.CLINICAS
  15 OF TABLASVARI  PASAJE DE TURNOS ENTRE H.CLINICAS
  16 OF TABLASVARI  CONTROL DE CALL
  1 OF TABLASVARI DO FORM FRMTURNO22 WITH  N
  2 OF TABLASVARI DO FORM FRMADMISION25
  3 OF TABLASVARI DO FORM FRMADMISION31
  4 OF TABLASVARI DO FORM FRMTURNO34
  5 OF TABLASVARI DO FORM FRMTURNO22 WITH  S
  7 OF TABLASVARI DO FORM FRMTURNO31
  8 OF TABLASVARI DO FORM FRMTURNO55
  9 OF TABLASVARI DO FORM FRMTURNO74
ON BAR 11 OF TABLASVARI ACTIVATE POPUP _1500LKZM2
  13 OF TABLASVARI DO FORM FRMTURNO76
  14 OF TABLASVARI DO FORM FRMTURNO52
  15 OF TABLASVARI DO FORM FRMTURNO61
  16 OF TABLASVARI DO FORM FRMTURNO93

DEFINE POPUP _1500LKZM2 MARGIN RELATIVE SHADOW COLOR SCHEME 4
  1 OF _1500LKZM2  RECEPCION
  2 OF _1500LKZM2  ASIGNACION DE TALONARIO
  3 OF _1500LKZM2  VALORIZACION
  4 OF _1500LKZM2  LISTADOS

  5 OF _1500LKZM2  ESTADO DE BONO

  1 OF _1500LKZM2 DO FORM FRMCAJA03
  3 OF _1500LKZM2 DO FORM FRMCAJA02
  4 OF _1500LKZM2 DO FORM FRMCAJA07
  5 OF _1500LKZM2 DO FORM FRMCAJA11

DEFINE POPUP PROFESIONA MARGIN RELATIVE SHADOW COLOR SCHEME 4
  1 OF PROFESIONA  AGENDA TELEFONICA
  2 OF PROFESIONA  \-
  3 OF PROFESIONA  ACTUALIZACION DE PROFESIONALES

  4 OF PROFESIONA  PRE REGISTRACION DE PROFESIONALES
  5 OF PROFESIONA  MODIFICACION DE BLOQUEOS
  6 OF PROFESIONA  \-
  7 OF PROFESIONA  MEDICO - PRESTACION
  8 OF PROFESIONA  BAJA DE PRESTACIONES
  9 OF PROFESIONA  COPIA DE FRANJAS
  10 OF PROFESIONA  COPIA DE FRANJAS ENTRE MEDICOS
  11 OF PROFESIONA  \-
  12 OF PROFESIONA  MEDICOS GERENCIADORAS
  1 OF PROFESIONA DO FORM FRMAGENDA_TEL
  3 OF PROFESIONA DO FORM FRMPRESTADORES
  4 OF PROFESIONA DO FORM FRMPRESTADORPR WITH 1
  5 OF PROFESIONA DO FORM FRMTURNO40
  7 OF PROFESIONA DO FORM FRMTURNO01
  8 OF PROFESIONA DO FORM FRMTURNO25
  9 OF PROFESIONA DO FORM FRMTURNO85
  10 OF PROFESIONA DO FORM FRMTURNO86
  12 OF PROFESIONA DO FORM FRMTURNO83

DEFINE POPUP MANEJODEAG MARGIN RELATIVE SHADOW COLOR SCHEME 4
  1 OF MANEJODEAG  GENERAR AGENDA
  2 OF MANEJODEAG  GENERAR AGENDA POR ESPECIALIDAD
  3 OF MANEJODEAG  GENERAR EXTENSION HORARIA
  4 OF MANEJODEAG  GENERAR AGENDA POR MEDICO
  5 OF MANEJODEAG  DESBLOQUEAR TURNOS
  6 OF MANEJODEAG  CONTROL DE TURNOS GENERADOS
  7 OF MANEJODEAG  OCUPACIÓN DE CONSULTORIOS
  8 OF MANEJODEAG  \-
  9 OF MANEJODEAG  ANULACIÓN TOTAL DE TURNOS
  10 OF MANEJODEAG  BLOQUEO DE TURNOS LIBRES
  11 OF MANEJODEAG  CANCELACION MASIVA DE TURNOS
  12 OF MANEJODEAG  REPROGRAMACION DE TURNOS
  13 OF MANEJODEAG  CONTROL DE REPROGRAMACIONES
  14 OF MANEJODEAG  REGISTRO DE LLAMADAS A PACIENTES
  15 OF MANEJODEAG  \-
  16 OF MANEJODEAG  RECUPERACIÓN T.CANCELADOS
  17 OF MANEJODEAG  \-
  18 OF MANEJODEAG  PASAR PS A TURNOS NORMALES
  19 OF MANEJODEAG  RETIPIFICACIÓN DE TURNOS
  20 OF MANEJODEAG  CARGA DE ST - SO - PS - GI - PE
  21 OF MANEJODEAG  \-
  22 OF MANEJODEAG  REIMPRESIÓN PLANILLAS MEDICOS
  23 OF MANEJODEAG  PLANILLAS KINESIOLOGIA
  1 OF MANEJODEAG DO FORM FRMTURNO02
  2 OF MANEJODEAG DO FORM FRMTURNO17
  3 OF MANEJODEAG DO FORM FRMTURNO44
  4 OF MANEJODEAG DO FORM FRMTURNO03
  5 OF MANEJODEAG DO FORM FRMTURNO81
  6 OF MANEJODEAG DO FORM FRMTURNO33
  7 OF MANEJODEAG DO FORM FRMTURNO72
  9 OF MANEJODEAG DO FORM FRMTURNO87
  10 OF MANEJODEAG DO FORM FRMTURNO87 WITH 1
  11 OF MANEJODEAG DO FORM FRMTURNO35
  12 OF MANEJODEAG DO FORM FRMTURNO13
  13 OF MANEJODEAG DO FORM FRMARCHIVO37
  14 OF MANEJODEAG DO FORM FRMTURNO90
  16 OF MANEJODEAG DO FORM FRMTURNO37
  18 OF MANEJODEAG DO FORM FRMTURNO45
  19 OF MANEJODEAG DO FORM FRMTURNO49
  20 OF MANEJODEAG DO FORM FRMTURNO27
  22 OF MANEJODEAG DO FORM FRMPHORARIAM
  23 OF MANEJODEAG DO FORM FRMTURNO15

DEFINE POPUP ESTADISTIC MARGIN RELATIVE SHADOW COLOR SCHEME 4
  1 OF ESTADISTIC  OFERTADOS VS OTORGADOS
  2 OF ESTADISTIC  PRESENTES VS AUSENTES
  3 OF ESTADISTIC  PE PRESENTES VS AUSENTES
  4 OF ESTADISTIC  RENDIMIENTO PROFESIONAL
  5 OF ESTADISTIC  RENDIMIENTO POR ESPECIALIDAD
  6 OF ESTADISTIC  TURNOS SOLICITADOS POR
  7 OF ESTADISTIC  TURNOS POR ENTIDAD
  8 OF ESTADISTIC  TURNOS GENERADOS
  9 OF ESTADISTIC  TURNOS CANCELADOS
  10 OF ESTADISTIC  TURNOS REPROGRAMADOS
  11 OF ESTADISTIC  TURNOS DADOS POR SECTOR
  12 OF ESTADISTIC  TURNOS DADOS POR ENTIDAD
  13 OF ESTADISTIC  MOVIMIENTOS POR SECTOR - USUARIO
  14 OF ESTADISTIC  CONSUMOS MEDICOS SOLICITANTES
  15 OF ESTADISTIC  LLAMADAS CALL CENTER
  16 OF ESTADISTIC  \-
  17 OF ESTADISTIC  AUSENTES POR ESPECIALIDAD
  18 OF ESTADISTIC  AUSENTES FONIATRÍA Y KINESIOLOGÍA
  19 OF ESTADISTIC  \-
  20 OF ESTADISTIC  H.CLINICAS UNIFICADAS
  21 OF ESTADISTIC  INFORME H.C.UNIF Y PASAJES CONSUMOS
  1 OF ESTADISTIC DO FORM FRMTURNO23
  2 OF ESTADISTIC DO FORM FRMTURNO26
  3 OF ESTADISTIC DO FORM FRMTURNO69
  4 OF ESTADISTIC DO FORM FRMTURNO78
  5 OF ESTADISTIC DO FORM FRMTURNO28
  6 OF ESTADISTIC DO FORM FRMTURNO32
  7 OF ESTADISTIC DO FORM FRMTURNO36
  8 OF ESTADISTIC DO FORM FRMTURNO29
  9 OF ESTADISTIC DO FORM FRMTURNO80
  10 OF ESTADISTIC DO FORM FRMTURNO79
  11 OF ESTADISTIC DO FORM FRMTURNO21
  12 OF ESTADISTIC DO FORM FRMTURNO54
  13 OF ESTADISTIC DO FORM FRMTURNO77
  14 OF ESTADISTIC DO FORM FRMTURNO57
  15 OF ESTADISTIC DO FORM FRMTURNO70
  17 OF ESTADISTIC DO FORM FRMTURNO53
  18 OF ESTADISTIC DO FORM FRMTURNO71
  20 OF ESTADISTIC DO FORM FRMTURNO88
  21 OF ESTADISTIC DO FORM FRMTURNO89

DEFINE POPUP TURNOS MARGIN RELATIVE SHADOW COLOR SCHEME 4
  1 OF TURNOS  DAR TURNOS
  1 OF TURNOS DO FORM FRMTURNO04
