MODIFY PROJECT c:\desaguemes\prj\administrador.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\admision.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\ambulatorio.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\autorizaciones.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\incidentes.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\pisos.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\launcher.pjx  nowait
MODIFY PROJECT c:\desaguemes\prj\quirofano.pjx  nowait
MODIFY PROJECT c:\desaguemes\prj\mesaadmision.pjx  nowait
MODIFY PROJECT c:\desaguemes\prj\facturacion.pjx  nowait
MODIFY PROJECT c:\desaguemes\prj\farmacia.pjx nowait
*MODIFY PROJECT c:\desaguemes\prj\calendario.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\mlaboral.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\prequirur.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\administrador.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\guardia.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\operaciones.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\prestadores.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\monitor1.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\preparadores.pjx nowait
MODIFY PROJECT c:\desaguemes\prj\teleconsulta.pjx nowait
*MODIFY PROJECT c:\desaguemes\prj\turnos.pjx nowait
